.github/workflows/ci.yaml
Node 8 is EOL and Node 10 is in _Maintenance LTS_ at the time of writing.
https://nodejs.org/en/about/releases/
=> Drop support for Node 8 and 10

.github/workflows/ci.yaml
Thanks to #31, I noticed that we weren't testing the bootstrapping/init
feature at all. This PR should make sure that the `userscripter` binary
can be installed globally and that we at least always generate a
userscript that can be built.
Resolves #32.
=> Test bootstrapping (`userscripter init`) in CI

src/build/internal/webpack.ts
`eval` in the built userscript doesn't work with some sites due to their CSP.
Resolves #30.
=> Fix Content Security Policy + eval issue

src/build/internal/configuration.ts, src/build/internal/webpack.ts
The constant overriding of version with `dateAsSemver` when in development can cause trouble when trying to create and e2e test the userscript using webextension (ex: chrome refuse to load a webextension with a version is not formated like `x.x.x`).
Even if we can build using `USERSCRIPTER_MODE=production` to fix the version issue. But that also minify the code, making the debuging/e2e tests writing harder.
So I simply added an option into the config to opt-out of this default behavior if needed.
=> feat: Make date suffix in version optional

bootstrap/metadata.ts, bootstrap/webpack.config.ts, src/bin/cli.ts, src/build/internal/webpack.ts, tslint.json
Would have become errors in the upcoming switch from TSLint to ESLint.
=> style: Fix import order and grouping (#52)

package-lock.json, package.json
Doesn't seem to break anything, at least not in Better SweClockers. And
TypeScript doesn't follow SemVer anyway.
=> chore: Upgrade to TypeScript 4 (#51)

bootstrap/tsconfig.json
Every single change I've tried to make lately has been blocked by an error in the `Bootstrap userscript` step (Node 14 and 16). Specifically, `npm run build` fails:
Error: node_modules/sass/types/legacy/function.d.ts(132,17): error TS1256: A rest element must be last in a tuple type.
The problem is that the build is not deterministic, since it uses `npm install`, not `npm ci` (which requires a `package-lock.json`). Userscripter's `package.json` specifies `"sass": "^1.32.8"`, so `npm install` will always install the latest version of Sass with major version 1 that happens to exist at that point in time.
On 2021-06-01, in [2cb85cb3] (so probably in version [1.34.1]), Sass added a declaration file containing the type `[...Value, (type: Value) => void]`, causing the error above. (`Value` was …
=> fix: Enable `skipLibCheck` in bootstrapped userscript

.github/workflows/ci.yaml
Node 14 went EOL on 2023-04-30, according to [Node's release schedule].
Also, the `Build userscript` step in CI fails with Node 14 for both dependent userscripts:
node_modules/sass/types/legacy/function.d.ts:132:17 - error TS1256: A rest element must be last in a tuple type.
132       ...args: [...LegacyValue[], LegacyAsyncFunctionDone]
~~~~~~~~~~~~~~~~
#86 suppressed that error in the bootstrapped userscript, but I don't know exactly if or how that is related to its occurrence in the dependent userscripts.
[Node's release schedule]: https://nodejs.dev/en/about/releases/
=> ci: Drop Node 14 support

package-lock.json
I did this:
$ npm --version
8.19.2
$ npm install --package-lock-only
Then `npm ci` failed with this error:
`npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
Invalid: lock file's acorn@5.7.4 does not satisfy acorn@8.8.2
Missing: acorn@5.7.4 from lock file
So I did `npm install` as recommended by npm.
This resolves the `old lockfile` warning emitted by `npm ci`:
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old …
=> build: Upgrade npm lockfile to version 2

src/build/internal/configuration.ts, src/build/internal/webpack.ts
We need to get rid of some complexity, and this option just isn't very useful in my experience.
=> feat!: Remove `allowJs` configuration option

package-lock.json, package.json
Version 3.2.5 removed `@types/schema-utils` in accordance with this warning that we, and all consumers, get on every `npm ci`:
npm WARN deprecated @types/schema-utils@2.4.0: This is a stub types definition. schema-utils provides its own type definitions, so you do not need this installed.
=> fix: Upgrade restrict-imports-loader to v3.2.5

.github/workflows/pr.yaml, package-lock.json, package.json
This version is breaking for any dependent userscripts that use the `allowJs` configuration option (#91).
The checked-in version number is changed from 1.3.3 to 2.0.0, but v1.4.0 and v1.5.0 also exist – just not on the trunk, but on a separate `v1` branch. Back then, the plan was to keep backporting features and fixes to older major versions, but I've abandoned those ambitions, since it's _a lot_ of work for little gain. From now on, new versions will only be released in a linear fashion.
Since we don't (yet) have automated releases (#66), this PR adapts the CI configuration to enable PRs like this one, whose subject start with a lowercase letter.
💡 `git show --color-words='[0-9.]+|.'`
=> chore: v2.0.0

src/build/webpack-userscript.d.ts
Should have been done in c8048d1c461a168d1672f0a7c9726fa77d357da5.
=> chore: Remove unused `webpack-userscript` module

__tests__/operations.test.ts, src/build/internal/webpack.ts, tsconfig.json
In my experience, the stricter the configuration is, the more value it brings, in general.
I've omitted `noUncheckedIndexedAccess` for now, because it causes non-trivial compilation errors in the existing code base.
💡 `git show --color-words=.`
=> build: Make TypeScript configuration stricter

package-lock.json, package.json, src/build/internal/webpack.ts
I think this feature adds more complexity than it does value. While I believe consumers won't have their builds broken (unless they have a test that checks what happens if they `import { … } from "userscripter/build"`), I'm making it a breaking change because it is a feature being removed after all.
=> feat!: Remove restrict-imports-loader

src/lib/operations.ts
I ran into a confusing problem in SimonAlling/better-sweclockers#264. Consider an operation with this implementation:
```typescript
export default (e: {
foo: HTMLElement,
bar: HTMLElement,
baz: HTMLElement,
}) => {
for (const element of Object.values(e)) {
console.log(element);
}
};
```
One would expect that all three elements would be logged, but this operation actually does nothing at all. The reason is that the properties of `e` aren't enumerable, so `Object.values(e)` is an empty array.
While it's easy to come up with pathological examples of operations that will be broken by this change, it should be backward compatible for all practical intents and purposes.
💡 `git show --color-words=.`
=> fix: Make properties of 'e' enumerable

package.json
This PR makes the public API explicit using `exports` and `typesVersions` in `package.json`. This should enable us to reorganize internal modules, compile to a `dist` directory etc without having to release (or consider releasing) a new major version.
I haven't been able to figure out any way to make TypeScript find the index module (when our consumer does `import … from "userscripter"`), except keeping the `main` field as is.
This is a backward compatible change as long as our consumer doesn't import anything from `bootstrap/` or `build/internal/`. That has never been intended to work, and it seems unlikely to me that anyone will have done that and expected it to be stable.
=> refactor: Declare exports in package.json

.github/workflows/ci.yaml
The tarball is more representative of what we actually ship.
=> ci: Install packed tarball instead of directory

package-lock.json, package.json
This release makes imports from `bootstrap/` and/or `build/internal/` (which have never been intended to work) TypeScript compilation errors (#105).
=> chore: v3.0.2

package-lock.json, package.json
I haven't been able to figure out why, or even if, we've ever actually needed it. For example, SimonAlling/better-sweclockers@b996a2b builds with Userscripter 1.0.0 with `loader-utils` and `@types/loader-utils` removed.
=> chore: Remove unused loader-utils dependency

package-lock.json, package.json
I haven't been able to figure out why, or even if, we've ever actually needed it. For example, SimonAlling/better-sweclockers@b996a2b builds with Userscripter 1.0.0 with `schema-utils` removed.
=> chore: Remove unused schema-utils dependency

package-lock.json, package.json
This release removes the `@types/loader-utils`, `loader-utils` and `schema-utils` dependencies, which seemingly aren't used for anything at all (#109, #110).
=> chore: v3.0.3

package.json
Today, it fails like this after `git clean -xdf`:
sh: 1: repository-check-dirty: not found
💡 `git show --color-words='npm ci|.'`
=> build: Improve 'verify' script

package-lock.json, package.json
I haven't been able to figure out why, or even if, we've ever actually needed it. For example, SimonAlling/better-sweclockers@b996a2b builds with Userscripter 1.0.0 with `@types/json-schema` removed.
=> chore: Remove unused @types/json-schema dependency

package-lock.json, package.json
This release removes the `@types/json-schema` dependency, which seemingly isn't used for anything at all (#114).
=> chore: v3.0.4

package-lock.json, package.json
This should make development more platform-independent, if not entirely so.
=> build: Use rimraf instead of 'rm -rf'

.eslintignore
The reason it works without it is that the sole `.ts` file created in `bin/` by `npm run build` contains nothing more than this:
#!/usr/bin/env node
export {};
So it basically just happens to pass our ESLint config. But it makes sense to ignore all compiled files.
=> chore: Add /bin/ to .eslintignore

package-lock.json, package.json
As far as I can tell, it has never been used for anything, except perhaps in an ad-hoc way. Since we don't use Prettier to check code formatting as part of any script or similar, I don't think it belongs as a dev dependency.
=> chore: Remove unused Prettier dev dependency

.github/workflows/ci.yaml
We're getting this warning in CI, in the Pack steps:
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Also, from now on, we won't be hard-wrapping commit messages at 72 characters anymore. I've changed the _Default commit message_ setting for the repository from _Pull request title and description_ to _Pull request title_; the description must be manually copied and pasted when merging because, unlike Azure DevOps, GitHub doesn't support using the description without hard-wrapping it.
💡 `git show --color-words=.`
=> ci: Use $GITHUB_OUTPUT instead of set-output

package-lock.json, package.json
This release adds a `package-lock.json` file to the bootstrapped userscript created by `userscripter init`, making dependency installations deterministic and enabling the use of `npm ci` (#123).
=> chore: v3.0.5

RELEASE.md
I've used this workflow for the last couple of releases. It's intentionally designed in a merge-then-publish fashion, so that we never end up publishing a package that wasn't built from a commit on the trunk. The downside is that it's possible to merge and tag a release commit from which we cannot publish, but I think that's much more acceptable.
=> docs: Document release workflow

bootstrap/package-lock-proxy.json, bootstrap/package.json
While this change might be breaking for users with specific expectations on the bootstrapped userscript, it is backward compatible at least in the sense that the commands in the _Create a new userscript_ section of the readme aren't affected.
I've decided to pin the exact version because a userscript is an application, not an npm package.
=> feat: Use v2.0.0 in bootstrapped userscript

package-lock.json, package.json
This release makes `userscripter init` bootstrap a userscript that uses version 2.0.0 of Userscripter.
=> chore: v3.1.0

bootstrap/package-lock-proxy.json, bootstrap/package.json
While this change might be breaking for users with specific expectations on the bootstrapped userscript, it is backward compatible at least in the sense that the commands in the _Create a new userscript_ section of the readme aren't affected.
=> feat: Use v3.0.5 in bootstrapped userscript

package-lock.json, package.json
This release makes `userscripter init` bootstrap a userscript that uses version 3.0.5 of Userscripter (#129).
=> chore: v3.2.0

.github/workflows/ci.yaml
The `fetch-depth` input seems to have been introduced in v2.
💡 `git show --color-words='v1|.'`
=> ci: Clone repos shallowly (`fetch-depth: 1`)

package-lock.json, package.json
This release removes the CLI tool used to create new userscripts. It shouldn't be breaking for existing userscripts, unless they `import … from "userscripter/bootstrap/…"` (which has never been intended to work; see #108) or run `userscripter init` for whatever reason.
Any invocations of `userscripter init` need to be replaced with a `tiged` command; see `README.md`.
=> chore: v4.0.0

.github/workflows/ci.yaml
Having CI suddenly break because a new version of Ubuntu has been released or whatever _sucks_. The more deterministic the builds, the better.
I chose 22.04 because we implicitly use that today (log says 22.04.4).
=> ci: Pin Ubuntu version

.github/workflows/ci.yaml
Having CI suddenly break because a new version of Node has been released or whatever _sucks_. The more deterministic the builds, the better.
I chose 16.20.2 because we implicitly use that today, according to the log.
In addition to the changes in this PR, I had to go to [the branch protection rule for `master`][rule] and replace **CI Build (16.x)** with **CI Build (16.20.2)** under _Require status checks to pass before merging_.
This PR is similar to #135.
[rule]: https://github.com/SimonAlling/userscripter/settings/branch_protection_rules/17488390
=> ci: Pin Node version

.github/workflows/ci.yaml
The current implementation may give the impression that checking the bootstrapped userscript somehow depends on checking and building the package first, but that's not the case.
In addition to the changes in this PR, I had to go to [the branch protection rule for `master`][rule] and add **Bootstrapped Userscript (16.20.2)** under _Require status checks to pass before merging_.
[rule]: https://github.com/SimonAlling/userscripter/settings/branch_protection_rules/17488390
=> ci: Check bootstrapped userscript in its own job

.github/workflows/ci.yaml
Before:
* Conventional Commits
* CI Build (16.20.2)
* Bootstrapped Userscript (16.20.2)
* Dependent Userscripts (SimonAlling/better-sweclockers, 16.20.2)
* Dependent Userscripts (SimonAlling/example-userscript, 16.20.2)
After:
* Conventional Commits
* Check package (Node 16.20.2)
* Check bootstrapped userscript (Node 16.20.2)
* Dependent: Better SweClockers (Node 16.20.2)
* Dependent: Example Userscript (Node 16.20.2)
In addition to the changes in this PR, I had to go to [the branch protection rule for `master`][rule] and update the required status checks under _Require status checks to pass before merging_.
[rule]: https://github.com/SimonAlling/userscripter/settings/branch_protection_rules/17488390
💡 `git show --color-words='CI Build|Bootstrapped Userscript| Userscripts|\w+|.'`
=> ci: Improve job names

.github/workflows/ci.yaml
The `bootstrap` job doesn't check how any changes to the library/package might affect the bootstrapped userscript; it only checks changes to the bootstrapped userscript itself (i.e. in `bootstrap/`). But we do want to know if a PR breaks the bootstrapped userscript, because then the PR may need to be considered breaking.
This PR therefore makes the bootstrapped userscript a so-called dependent userscript, just like Better SweClockers and Example Userscript. Building dependent userscripts deliberately isn't a _gating_ check because, as previously explained in #68, the purpose isn't to prevent _deliberate_ breaking changes, just _accidental_ ones.
💡 `git show --color-words=.`
=> ci: Make bootstrapped userscript dependent

bootstrap/package-lock.json, bootstrap/package.json
This change is definitely not breaking, because v4.0.0 removed the CLI tool (`userscripter init`). That is, any expectations on the bootstrapped userscript that users might have are completely irrelevant when it comes to versioning the npm package.
=> chore: Use v4.0.0 in bootstrapped userscript

RELEASE.md
I used this workflow in #140. It ensures that the recommended way of bootstrapping a new userscript (the `tiged` command in `README.md`) will always work, including when a release PR has been merged but a corresponding version of the package hasn't been published to the npm registry (either because it hasn't been done yet or because it cannot be done at all for whatever reason).
=> docs: Update bootstrapped userscript post-release

RELEASE.md
When viewing the file on GitHub, it's rendered as if `[!WARNING]` doesn't have any special meaning at all. Turns out [alerts cannot be indented], so I guess this is the best we can do for now.
[alerts cannot be indented]: https://github.com/orgs/community/discussions/118296
=> docs: Hotfix broken warning alert

package-lock.json, package.json
TypeScript doesn't use SemVer – one should think of e.g. v4.2 and v4.3 as v42 and v43, respectively – so `^4.2.3` makes no sense. `~4.2.3` does, but it usually doesn't hurt to specify an exact version in my experience.
=> build: Pin TypeScript version

package-lock.json, package.json
This will enable upgrading to Jest 26 (#144; see #145).
See #145 for details on why this should possibly be considered a breaking change.
I consider it backward compatible, because I don't think any consumer is broken by it. Notably, building with and without this PR in different Git working trees and using `git diff --no-index` to diff the emitted code (`build/` and `lib/`) reveals that the only difference is that some expressions in `.js` files are transformed from `foo` to `(0, foo)`.
=> build: Upgrade to TypeScript 4.4

package-lock.json, package.json
This decreases the number of vulnerabilities according to `npm audit`:
* **Before:** 58 vulnerabilities (1 low, 16 moderate, 39 high, 2 critical)
* **After:** 40 vulnerabilities (1 low, 8 moderate, 30 high, 1 critical)
I made the changes like this:
npm install --save-dev --save-exact jest@26 @types/jest@26 ts-jest@26
I deliberately pinned the versions because that makes sense for development tools like Jest.
I picked version 26 because I got this error with version 25:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: userscripter@4.0.0
npm ERR! Found: typescript@4.4.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"4.4.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer …
=> build: Upgrade to Jest 26

package-lock.json, package.json
This decreases the number of vulnerabilities according to `npm audit`:
* **Before:** 40 vulnerabilities (1 low, 8 moderate, 30 high, 1 critical)
* **After:** 22 vulnerabilities (1 low, 8 moderate, 13 high)
I made the changes like this:
npm install --save-dev --save-exact jest@27 @types/jest@27 ts-jest@27
Then `npm test` failed with this error:
The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string. Consider using the "jsdom" test environment.
ReferenceError: document is not defined
So I set the test environment to `"jsdom"`.
=> build: Upgrade to Jest 27

jest.config.mjs, package.json
Specifying the file with `--config` isn't necessary, but I like to be explicit.
💡 `git show --color-moved --color-moved-ws=allow-indentation-change`
=> build: Move Jest configuration to its own file

__tests__/api.test.ts
With Jest 27 (#147), the `exposes everything in lib in index.ts` test case started behaving weirdly in situations when it should fail. For example, creating `src/lib/foo.ts` causes `npm test` to fail like this after about 10 seconds (which is longer than usual):
● exposes everything in lib in index.ts
expect(received).toEqual(expected) // deep equality
- Expected  - 0
+ Received  + 1
@@ -1,8 +1,9 @@
Array [
"environment.ts",
"errors.ts",
+   "foo.ts",
"index.ts",
"log.ts",
"operations.ts",
"preferences.ts",
"stylesheets.ts",
[…]
● exposes everything in lib in index.ts
thrown: "Exceeded timeout of 5000 ms for a test.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
The `expect` failure is expected, but the timeout is unexpected and doesn't …
=> test: Use async/await instead of 'done' callback

package-lock.json, package.json
This will enable upgrading to Jest 29, which [requires] TypeScript 4.5 if `jest-environment-jsdom` is used.
I did this:
npm install --save-dev --save-exact typescript@4.5
Then I got this warning when running `npm run lint`:
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0
YOUR TYPESCRIPT VERSION: 4.5.5
Please only submit bug reports when using the officially supported version.
So I did this:
npm install --save-dev @typescript-eslint/eslint-plugin@^4
It didn't help, so I did this:
npm install --save-dev @typescript-eslint/eslint-plugin@^5 @typescript-eslint/parser@^5
See #145 for details on why this should …
=> build: Upgrade to TypeScript 4.5

package-lock.json, package.json
This release renames the `build` and `lib` export paths to `build-time` and `run-time`, respectively (#104).
You need to adapt your imports like this:
* ```diff
-import … from "userscripter/build";
+import … from "userscripter/build-time";
```
* ```diff
-import … from "userscripter/lib/foo";
+import … from "userscripter/run-time/foo";
```
This command should accomplish that in a typical Git-tracked userscript:
```bash
for f in $(git ls-files "$(git rev-parse --show-toplevel)"); do
sed -i 's#userscripter/build#userscripter/build-time#g' $f
sed -i 's#userscripter/lib#userscripter/run-time#g' $f
done
```
=> chore: v5.0.0

bootstrap/metadata.ts, bootstrap/package-lock.json, bootstrap/package.json, bootstrap/src/operations.ts, bootstrap/src/preferences.ts, bootstrap/src/stylesheets.ts, bootstrap/webpack.config.ts
I used the command suggested in #153 to adapt the source code.
💡 `git show --color-words='build-time|(\w|\+|=)+|.'`
=> chore: Use v5.0.0 in bootstrapped userscript

bootstrap/package-lock.json, bootstrap/package.json
We use TypeScript 4.5 to compile the package itself since #151 (v5.0.0), so it makes sense to use at least that version in the bootstrapped userscript as well.
I did `npm install --save-exact typescript@4.5` because it typically makes much more sense to specify an exact TypeScript version than to specify a version range.
=> chore: Use TypeScript 4.5 in bootstrapped userscript

package-lock.json, package.json
A typical userscript doesn't need it because it doesn't import anything from the `terser-webpack-plugin` package; I therefore consider this a backward-compatible change.
I did this:
$ npm why @types/terser-webpack-plugin
@types/terser-webpack-plugin@2.2.0
node_modules/@types/terser-webpack-plugin
@types/terser-webpack-plugin@"^2.2.0" from the root project
$ npm remove @types/terser-webpack-plugin
$ npm install --save-dev --save-exact @types/terser-webpack-plugin@2.2.0
=> chore: Remove @types/terser-webpack-plugin dependency

package-lock.json, package.json
webpack [recommends] upgrading to the latest 4.x version before upgrading to webpack 5.
I did this:
npm install webpack@4 @types/webpack@4
[recommends]: https://webpack.js.org/migrate/5/#upgrade-webpack-4-and-its-pluginsloaders
=> chore: Upgrade to webpack 4.47

src/build-time/internal/webpack.ts
I think this will make it easier to upgrade `css-loader`, which in turn I think will be necessary in order to upgrade to webpack 5.
At the time of writing, the latest version of `css-loader` that matches `^3.2.0` – and the one used in the bootstrapped userscript, SimonAlling/example-userscript@d1d30ea5 and SimonAlling/better-sweclockers@7381699f, according to `npm why` – is **3.6.0**. I went [here] to check what its default options are, and then I specified them. For some of them, the documented default value isn't obviously correct/sensible:
* ### `hashPrefix`
The documented default value is `undefined`, but based on [the source code][hashPrefix], it's actually `""`. That makes much more sense to me too.
* ### `getLocalIdent`
The documented default value is `undefined`, but specifying …
=> refactor: Specify css-loader options

package-lock.json, package.json
Yeah, how does one even document this …
When I recently returned to this project after not having touched it since 2024-08-01 (#161), suddenly CI would fail, without any changes having been made. The failure happened in the **Dependent: Bootstrapped Userscript (Node 16.20.2)** job, in the **Build userscript** step:
> build-webpack-config
> tsc -p tsconfig.webpack.json
Error: node_modules/@types/node/http.d.ts(236,47): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(236,71): error TS1109: Expression expected.
Error: node_modules/@types/node/http.d.ts(237,5): error TS1109: Expression expected.
Error: node_modules/@types/node/http.d.ts(241,46): error TS1005: ',' expected.
[…]
I guess the type declaration files in question use TypeScript syntax that can't be parsed by …
=> fix: Add @types/node@16.18.31 as dependency

package-lock.json, package.json
This release makes `userscripter init` bootstrap a userscript that uses TypeScript 4.5 (#155) and webpack 4.47.0 (#159). It also makes consumers get version 16.18.31 of `@types/node` (#165).
=> chore: v5.1.0

.github/workflows/ci.yaml
After #164, I want to minimize non-determinism as far as practically possible. In particular, I absolutely don't want CI to suddenly fail without any changes in this repo, just because some change has been made in a dependent userscript.
=> ci: Use deterministic versions of dependent userscripts

.github/workflows/ci.yaml
Node 16 [has been EOL since 2023-09-11][eol]. The current Active LTS [is Node 22][active].
In addition to the changes in this PR, I had to go to [the branch protection rule for `master`][rule] and update the required status checks under _Require status checks to pass before merging_.
[eol]: https://nodejs.org/en/blog/announcements/nodejs16-eol
[active]: https://nodejs.org/en/about/previous-releases
[rule]: https://github.com/SimonAlling/userscripter/settings/branch_protection_rules/17488390
=> ci!: Support Node 22; drop Node 16 support

package-lock.json, package.json
This release drops support for Node 16 in favor of Node 22.
You should migrate to Node 22 in your development environment to avoid any potential breakage in upcoming non-major releases.
=> chore: v6.0.0

.github/workflows/ci.yaml
The purpose of building dependent userscripts in CI is to identify breaking changes before merging them. This PR updates the dependent userscripts to versions with Userscripter 6.0.0 (see SimonAlling/better-sweclockers#275 and SimonAlling/example-userscript#33), so that breaking changes are identified relative to the current major release, which is the entire point.
=> ci: Update dependent userscripts

src/build-time/internal/sass.ts, tsconfig.json
The source-code changes are made in direct response to type errors exposed by `noUncheckedIndexedAccess`.
=> build: Enable noUncheckedIndexedAccess

package-lock.json, package.json
While this probably doesn't break any existing userscripts, I consider this a BREAKING change because upgrading to a new TypeScript version means that future changes might accidentally introduce syntax not supported by earlier versions. Also, I'm looking into [Semantic Versioning for TypeScript Types](https://www.semver-ts.org), which lists two "recommended support policies for TypeScript compiler versions":
> * In _simple majors_, dropping support for a previously supported compiler version requires a breaking change.
>
> * In _rolling window_, a package may declare a range of supported versions which moves over time, similar to supporting evergreen browsers.
In the absence of a documented support policy, I think it makes sense to default to _simple majors_.
=> build!: Upgrade to TypeScript 5.0
